PACKAGE_NAME="wujie14x-uniwill"
PACKAGE_VERSION="@PACKAGE_VERSION@"
BUILT_MODULE_NAME[0]="uniwill-laptop"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"

MAKE[0]="make -C /usr/lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
